# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-19.32

# User packages to be built.
packages:
- .

# Dependency packages to be pulled from upstream that are not in the resolver.
extra-deps:
  - hspec-wai-json-0.11.0
